### ISSUE TITLE
내용복사가 엉뚱하게 이뤄지는 경우가 있습니다.

### ISSUE THREAD

**Issue by DSonDH** [JunghyunHwang/PleaseShareYourCode#1]
안녕하세요,
PSYC 잘 쓰다가 버그 하나 발견하여 이슈 올립니다.

COMP 2500 lab6과제 내용을 추출할 때
아래처럼 Pizza.java부분 코드가 FreeSoulPizza.java내용으로 덮어씌워지네요

```
//----------------------Pizza.java----------------------
​
package academy.pocu.comp2500.lab6;
​
public class FreeSoulPizza extends Pizza {
​
    public FreeSoulPizza() {
        ...

```

//----------------------FreeSoulPizza.java----------------------
에 적힐 내용은 제대로 적히고 있습니다.
Pizza.java부분만 이상하게 추출되는 것입니다.

감사합니다.

**Comment by DSonDH** [comment]
이건 다른 얘기긴 한데요, 
https://docs.google.com/document/d/1htU20ynckoBCVjZoKyCZ85lWflPBinkvCr9ORYsy4OM/edit
에 맨 아래 사용 예시 그림이 COMP2500과제1 답안 일부라 
혹시 누군가에겐 스포가 되지는 않을까 싶어서 함께 말씀 드립니다.

감사합니다!

**Comment by JunghyunHwang** [comment]
버그 제보 감사드립니다!🙏
1. 버그 확인하고 수정했습니다. 1.0.4 버전으로 재설치 후 실행해주세요. 감사합니다.
2. COMP2500 과목이 개체지향과 "설계" 까지 포함된 과목이니 말씀하신 부분이 맞다고 판단하여 문서 수정했습니다.
